<?php
/* 
 * include file to hide my username and password, the actual file name will 
 * be your username. Look at this web site:
 * 
 * http://webdb.uvm.edu/web_publishing.php
 * 
 * This file needs to be emailed to the system administrators (see web site)
 * 
 * BE SURE YOU DO NOT HAVE ANY BLANK LINES BEFORE OR AFTER YOUR OPENING
 * AND CLOSING PHP TAGS.
 */

  $db_name = 'BYARDLEY_climbing';

  $db_R_username = 'byardley_reader';
  $db_R_password = 'd01HktjDCJ79';
  
  $db_W_username = 'byardley_writer';
  $db_W_password = 'cJyehN9kbHsy';

  $db_A_username = 'byardley_admin';
  $db_A_password = 'williston1992';

?>